### ISSUE TITLE
Reduce draw impact

### ISSUE THREAD

**Issue by Kender2** [Kender2/swc-squadranking#9]
Currently draws have a huge impact on the skill ratings.
Due to the nature of the game (that allows draws) and the outposts which sometimes make a draw almost inevitable the result can be quite severe and unfair.
But a draw is often also the only way a lower ranked squad can go against a much higher ranked squad.

Possible things to try:
1. make a draw only affect the lowest ranked squad
2. change the DRAW_PROBABILITY constant around to see the effect it has on ratings
3. ??? 

This may mean a recalculating of all the ratings when we've found a suitable solution.

**Comment by MidgetAl** [comment]
I definitely think a small adjustment to this would make a big difference. I don't know how, but a 45-45 draw probably shouldn't make you tumble 3500 spots ... I am not a programmer though ... just a suggester :)

**Comment by Kender2** [comment]
Current plan is to not count 45-45 results at all, since they basically say nothing about the skill of either team.
Other ties like 33-33 will continue to function as normal since that does say something about the skills of the squads.
The tricky part is that that means that all the scores have to be recalculated, whihc will mean a couple (?) of hours of downtime.

**Comment by Kender2** [comment]
Fixed in 9b88c1019747332bd211bcf35b149939f8a1a019

**Comment by MidgetAl** [comment]
Well ... this ended up hurting my squad :( But I agree with the sentiment as a whole. We had a couple 45-45 draws against really good squads. But, I don't think it showed much skill, just showed how ridiculous Tako is.
